services:
  - type: web
    name: email-validator-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: RAPIDAPI_PROXY_SECRET
        sync: false
